{"timestamp":"2025-10-29T12:17:52.550867","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-10-29T12:17:52.552210","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/Airflow.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-10-29T12:17:52.612139","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:17:52.613872","level":"info","event":"Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/DWD_ICON_EU.py']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:17:52.633146","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:17:56.120577","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:17:58.573249","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.416613","level":"info","event":"üîÑ Descargando datos de http://host.docker.internal:8081/v1/forecast ...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.416977","level":"info","event":"‚¨áÔ∏è Descargando temperature_2m del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.417347","level":"info","event":"‚¨áÔ∏è Descargando precipitation del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.417590","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6bc105a30>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.417937","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec8980>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.418194","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9040>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.418581","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9910>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.418895","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7eca030>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.419158","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6ef06cf20>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.419506","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9970>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.419811","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9520>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.420136","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9400>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.420362","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7eca840>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.420797","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ecb1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.421159","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ea2000>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.421837","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ecb890>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.422221","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9070>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.422496","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec95e0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.422841","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9640>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.423047","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7eca180>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.423263","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6ef0c2ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.423491","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec8e00>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.423710","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec99a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.424052","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9670>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.424206","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ecaff0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.489868","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ecb350>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.490245","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7f0c290>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.490409","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ecb740>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.490541","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ecb050>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.490740","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec8e30>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.490878","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec8da0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.490994","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9d90>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.491110","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6c547b6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.491301","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec9e80>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.491423","level":"info","event":"HTTPConnectionPool(host='host.docker.internal', port=8081): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d6b7ec90d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.491610","level":"info","event":"","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.491986","level":"info","event":"üèÅ Descarga completada en 5.05 s (0.08 min)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.492155","level":"info","event":"‚ùå No se obtuvieron datos.","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.492298","level":"info","event":"Traceback (most recent call last):","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.492476","level":"info","event":"  File \"/opt/airflow/scripts/DWD_ICON_EU.py\", line 182, in <module>","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.492626","level":"info","event":"    main()","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.492741","level":"info","event":"  File \"/opt/airflow/scripts/DWD_ICON_EU.py\", line 169, in main","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.492862","level":"info","event":"    timestamp = df[\"time\"].tolist(),","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.493035","level":"info","event":"                ~~^^^^^^^^","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.493176","level":"info","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 3893, in __getitem__","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.493293","level":"info","event":"    indexer = self.columns.get_loc(key)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.493403","level":"info","event":"              ^^^^^^^^^^^^^^^^^^^^^^^^^","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.493565","level":"info","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/range.py\", line 418, in get_loc","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.493735","level":"info","event":"    raise KeyError(key)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.493855","level":"info","event":"KeyError: 'time'","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.689815","level":"info","event":"Command exited with return code 1","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T12:18:00.691123","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowException","exc_value":"Bash command failed. The command returned a non-zero exit code 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/bash.py","lineno":232,"name":"execute"}],"is_group":false,"exceptions":[]}]}
