{"timestamp":"2025-10-29T11:46:01.716693","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-10-29T11:46:01.717926","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/Airflow.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-10-29T11:46:01.789168","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:01.790598","level":"info","event":"Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/ARPEGE.py']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:01.811159","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:06.441769","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:09.230614","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:12.180175","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:15.091396","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.007700","level":"info","event":"üîÑ Descargando datos de http://127.0.0.1:8080/v1/forecast ...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.008148","level":"info","event":"‚¨áÔ∏è Descargando temperature_2m del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.008427","level":"info","event":"‚¨áÔ∏è Descargando precipitation del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.008663","level":"info","event":"‚¨áÔ∏è Descargando relative_humidity_2m del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.008897","level":"info","event":"‚¨áÔ∏è Descargando shortwave_radiation del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.009173","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ed3da060>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.009403","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510a10>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.009646","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.009858","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65117c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.010305","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.010576","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e75b3020>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.010779","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ec05b4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.011100","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511a60>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.011345","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511130>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.011527","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65128d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.011726","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6513260>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.011900","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e66d5280>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.012093","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6513260>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.012309","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510a10>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.012484","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.012650","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511a00>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.012814","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6513890>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.012976","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6785490>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.013229","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ecbb8770>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.013449","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511760>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.013624","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.075116","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6512960>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.075648","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65132c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.076035","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65541d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.076338","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ec1d8860>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.076635","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510a10>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.076889","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.077142","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511580>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.077383","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6512210>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.077662","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6787e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.077905","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ed44f5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.080730","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6513830>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.080989","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511070>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.081317","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6512b70>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.081556","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65129c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.081765","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65542c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.082004","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510a10>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.082281","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511010>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.082515","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65117c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.082727","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ecac77a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.082933","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6554500>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.083136","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6554e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.083391","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ed400a40>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.083598","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511040>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.131167","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65127b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.131560","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6512c90>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.131814","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65544d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.132053","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6555820>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.132312","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.132532","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6512750>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.132764","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.133001","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4ec2d6f00>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.133263","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65559a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.133475","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65552e0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.133638","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e66d5280>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.133775","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.134017","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6510ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.134291","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6512b40>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.134465","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511a30>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.134588","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6555b20>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.134744","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6513020>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.134928","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6512a80>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.135114","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=relative_humidity_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e6511370>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.135353","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=meteofrance_arpege_europe&hourly=shortwave_radiation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76a4e65121b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.135600","level":"info","event":"","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.135882","level":"info","event":"üèÅ Descarga completada en 11.47 s (0.19 min)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.136134","level":"info","event":"‚ùå No se obtuvieron datos.","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.136360","level":"info","event":"Traceback (most recent call last):","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.136564","level":"info","event":"  File \"/opt/airflow/scripts/ARPEGE.py\", line 177, in <module>","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.136817","level":"info","event":"    main()","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.137045","level":"info","event":"  File \"/opt/airflow/scripts/ARPEGE.py\", line 157, in main","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.137257","level":"info","event":"    df = df.dropna(subset=VARIABLES) # Borra las filas con datos de las variables faltantes que corresponden a predicciones no disponibles.","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.137488","level":"info","event":"         ^^^^^^^^^^^^^^^^^^^^^^^^^^^","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.137744","level":"info","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 6418, in dropna","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.138185","level":"info","event":"    raise KeyError(np.array(subset)[check].tolist())","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.138427","level":"info","event":"KeyError: ['temperature_2m', 'precipitation', 'relative_humidity_2m', 'shortwave_radiation']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.434817","level":"info","event":"Command exited with return code 1","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:17.436217","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowException","exc_value":"Bash command failed. The command returned a non-zero exit code 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/bash.py","lineno":232,"name":"execute"}],"is_group":false,"exceptions":[]}]}
