{"timestamp":"2025-10-29T11:46:01.820597","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-10-29T11:46:01.823988","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/Airflow.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-10-29T11:46:02.076470","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:02.107861","level":"info","event":"Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/DWD_ICON_EU.py']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:02.129704","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:06.546285","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:09.026952","level":"info","event":"[ INFO ] Checking for files to with more than 7 past days data","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.837756","level":"info","event":"üîÑ Descargando datos de http://127.0.0.1:8080/v1/forecast ...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.838291","level":"info","event":"‚¨áÔ∏è Descargando temperature_2m del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.838709","level":"info","event":"‚¨áÔ∏è Descargando precipitation del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.839300","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5f24e090>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.840395","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb4680>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.840795","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb4e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.842124","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5670>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.842505","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5d90>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.842775","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f653c0590>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.843087","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5970>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.843338","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb53d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.843680","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5160>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.843984","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb6600>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.844254","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb6f30>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.844490","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5db93b00>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.844854","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb56a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.845270","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb4620>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.845548","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5160>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.845870","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=39.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5580>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.849095","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb61e0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.849496","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5ec579b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.849802","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb49b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.850151","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb6000>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.850509","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5040>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.850784","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb6fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.873814","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb6a80>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.874192","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbf80b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.874494","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb4950>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.874763","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb5700>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.875057","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb6630>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.875286","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb6360>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.875582","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb4a40>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.875823","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-1.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5ec57440>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.876101","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=temperature_2m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb4ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.876306","level":"info","event":"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/forecast?latitude=40.1281556&longitude=-0.5212770999999998&models=dwd_icon_eu&hourly=precipitation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x796f5dbb4860>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.876566","level":"info","event":"","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.876772","level":"info","event":"üèÅ Descarga completada en 5.13 s (0.09 min)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.876967","level":"info","event":"‚ùå No se obtuvieron datos.","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.877448","level":"info","event":"Traceback (most recent call last):","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.877681","level":"info","event":"  File \"/opt/airflow/scripts/DWD_ICON_EU.py\", line 182, in <module>","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.878047","level":"info","event":"    main()","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.878289","level":"info","event":"  File \"/opt/airflow/scripts/DWD_ICON_EU.py\", line 169, in main","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.878600","level":"info","event":"    timestamp = df[\"time\"].tolist(),","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.878854","level":"info","event":"                ~~^^^^^^^^","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.879137","level":"info","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 3893, in __getitem__","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.879363","level":"info","event":"    indexer = self.columns.get_loc(key)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.879641","level":"info","event":"              ^^^^^^^^^^^^^^^^^^^^^^^^^","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.879855","level":"info","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/range.py\", line 418, in get_loc","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.880247","level":"info","event":"    raise KeyError(key)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:10.880547","level":"info","event":"KeyError: 'time'","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:11.224716","level":"info","event":"Command exited with return code 1","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-29T11:46:11.227988","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowException","exc_value":"Bash command failed. The command returned a non-zero exit code 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/bash.py","lineno":232,"name":"execute"}],"is_group":false,"exceptions":[]}]}
